# Generated by Django 5.1.3 on 2025-04-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_category_created_at_category_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="price",
            new_name="stock",
        ),
    ]
