# Generated by Django 5.1.3 on 2025-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_price_productvariant_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="drop",
            field=models.TextField(default="drop 001"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                default="https://example.com/default.jpg", max_length=500
            ),
        ),
    ]
