# Generated by Django 5.1.3 on 2025-05-07 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_drop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="drop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.drop",
            ),
        ),
    ]
