# Generated by Django 5.1.3 on 2025-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_drop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(
                choices=[("W", "White"), ("R", "RED"), ("B", "Blue"), ("BL", "BLACK")],
                max_length=10,
            ),
        ),
    ]
