# Generated by Django 5.1.3 on 2025-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_product_stock_alter_productvariant_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(
                choices=[
                    ("W", "White"),
                    ("R", "RED"),
                    ("B", "Blue"),
                    ("BL", "BLACK"),
                    ("G", "GREY"),
                ],
                max_length=10,
            ),
        ),
    ]
